// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: v2/hcore/hcore.proto

package hcore

import (
	hcommon "github.com/TwilgateLabs/inhive-core/v2/hcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoreStates int32

const (
	CoreStates_STOPPED  CoreStates = 0
	CoreStates_STARTING CoreStates = 1
	CoreStates_STARTED  CoreStates = 2
	CoreStates_STOPPING CoreStates = 3
)

// Enum value maps for CoreStates.
var (
	CoreStates_name = map[int32]string{
		0: "STOPPED",
		1: "STARTING",
		2: "STARTED",
		3: "STOPPING",
	}
	CoreStates_value = map[string]int32{
		"STOPPED":  0,
		"STARTING": 1,
		"STARTED":  2,
		"STOPPING": 3,
	}
)

func (x CoreStates) Enum() *CoreStates {
	p := new(CoreStates)
	*p = x
	return p
}

func (x CoreStates) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoreStates) Descriptor() protoreflect.EnumDescriptor {
	return file_v2_hcore_hcore_proto_enumTypes[0].Descriptor()
}

func (CoreStates) Type() protoreflect.EnumType {
	return &file_v2_hcore_hcore_proto_enumTypes[0]
}

func (x CoreStates) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoreStates.Descriptor instead.
func (CoreStates) EnumDescriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_EMPTY                 MessageType = 0
	MessageType_EMPTY_CONFIGURATION   MessageType = 1
	MessageType_START_COMMAND_SERVER  MessageType = 2
	MessageType_CREATE_SERVICE        MessageType = 3
	MessageType_START_SERVICE         MessageType = 4
	MessageType_UNEXPECTED_ERROR      MessageType = 5
	MessageType_ALREADY_STARTED       MessageType = 6
	MessageType_ALREADY_STOPPED       MessageType = 7
	MessageType_INSTANCE_NOT_FOUND    MessageType = 8
	MessageType_INSTANCE_NOT_STOPPED  MessageType = 9
	MessageType_INSTANCE_NOT_STARTED  MessageType = 10
	MessageType_ERROR_BUILDING_CONFIG MessageType = 11
	MessageType_ERROR_PARSING_CONFIG  MessageType = 12
	MessageType_ERROR_READING_CONFIG  MessageType = 13
	MessageType_ERROR_EXTENSION       MessageType = 14
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "EMPTY",
		1:  "EMPTY_CONFIGURATION",
		2:  "START_COMMAND_SERVER",
		3:  "CREATE_SERVICE",
		4:  "START_SERVICE",
		5:  "UNEXPECTED_ERROR",
		6:  "ALREADY_STARTED",
		7:  "ALREADY_STOPPED",
		8:  "INSTANCE_NOT_FOUND",
		9:  "INSTANCE_NOT_STOPPED",
		10: "INSTANCE_NOT_STARTED",
		11: "ERROR_BUILDING_CONFIG",
		12: "ERROR_PARSING_CONFIG",
		13: "ERROR_READING_CONFIG",
		14: "ERROR_EXTENSION",
	}
	MessageType_value = map[string]int32{
		"EMPTY":                 0,
		"EMPTY_CONFIGURATION":   1,
		"START_COMMAND_SERVER":  2,
		"CREATE_SERVICE":        3,
		"START_SERVICE":         4,
		"UNEXPECTED_ERROR":      5,
		"ALREADY_STARTED":       6,
		"ALREADY_STOPPED":       7,
		"INSTANCE_NOT_FOUND":    8,
		"INSTANCE_NOT_STOPPED":  9,
		"INSTANCE_NOT_STARTED":  10,
		"ERROR_BUILDING_CONFIG": 11,
		"ERROR_PARSING_CONFIG":  12,
		"ERROR_READING_CONFIG":  13,
		"ERROR_EXTENSION":       14,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_v2_hcore_hcore_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_v2_hcore_hcore_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{1}
}

type SetupMode int32

const (
	SetupMode_OLD                      SetupMode = 0
	SetupMode_GRPC_NORMAL              SetupMode = 1
	SetupMode_GRPC_BACKGROUND          SetupMode = 2
	SetupMode_GRPC_NORMAL_INSECURE     SetupMode = 3
	SetupMode_GRPC_BACKGROUND_INSECURE SetupMode = 4
)

// Enum value maps for SetupMode.
var (
	SetupMode_name = map[int32]string{
		0: "OLD",
		1: "GRPC_NORMAL",
		2: "GRPC_BACKGROUND",
		3: "GRPC_NORMAL_INSECURE",
		4: "GRPC_BACKGROUND_INSECURE",
	}
	SetupMode_value = map[string]int32{
		"OLD":                      0,
		"GRPC_NORMAL":              1,
		"GRPC_BACKGROUND":          2,
		"GRPC_NORMAL_INSECURE":     3,
		"GRPC_BACKGROUND_INSECURE": 4,
	}
)

func (x SetupMode) Enum() *SetupMode {
	p := new(SetupMode)
	*p = x
	return p
}

func (x SetupMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetupMode) Descriptor() protoreflect.EnumDescriptor {
	return file_v2_hcore_hcore_proto_enumTypes[2].Descriptor()
}

func (SetupMode) Type() protoreflect.EnumType {
	return &file_v2_hcore_hcore_proto_enumTypes[2]
}

func (x SetupMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetupMode.Descriptor instead.
func (SetupMode) EnumDescriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{2}
}

type LogLevel int32

const (
	LogLevel_TRACE   LogLevel = 0
	LogLevel_DEBUG   LogLevel = 1
	LogLevel_INFO    LogLevel = 2
	LogLevel_WARNING LogLevel = 3
	LogLevel_ERROR   LogLevel = 4
	LogLevel_FATAL   LogLevel = 5
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "TRACE",
		1: "DEBUG",
		2: "INFO",
		3: "WARNING",
		4: "ERROR",
		5: "FATAL",
	}
	LogLevel_value = map[string]int32{
		"TRACE":   0,
		"DEBUG":   1,
		"INFO":    2,
		"WARNING": 3,
		"ERROR":   4,
		"FATAL":   5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_v2_hcore_hcore_proto_enumTypes[3].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_v2_hcore_hcore_proto_enumTypes[3]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{3}
}

type LogType int32

const (
	LogType_CORE    LogType = 0
	LogType_SERVICE LogType = 1
	LogType_CONFIG  LogType = 2
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "CORE",
		1: "SERVICE",
		2: "CONFIG",
	}
	LogType_value = map[string]int32{
		"CORE":    0,
		"SERVICE": 1,
		"CONFIG":  2,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_v2_hcore_hcore_proto_enumTypes[4].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_v2_hcore_hcore_proto_enumTypes[4]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{4}
}

type CoreInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoreState     CoreStates             `protobuf:"varint,1,opt,name=core_state,json=coreState,proto3,enum=hcore.CoreStates" json:"core_state,omitempty"`
	MessageType   MessageType            `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,enum=hcore.MessageType" json:"message_type,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreInfoResponse) Reset() {
	*x = CoreInfoResponse{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreInfoResponse) ProtoMessage() {}

func (x *CoreInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreInfoResponse.ProtoReflect.Descriptor instead.
func (*CoreInfoResponse) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{0}
}

func (x *CoreInfoResponse) GetCoreState() CoreStates {
	if x != nil {
		return x.CoreState
	}
	return CoreStates_STOPPED
}

func (x *CoreInfoResponse) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_EMPTY
}

func (x *CoreInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath             string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	ConfigContent          string                 `protobuf:"bytes,2,opt,name=config_content,json=configContent,proto3" json:"config_content,omitempty"` // Optional if configPath is not provided.
	DisableMemoryLimit     bool                   `protobuf:"varint,3,opt,name=disable_memory_limit,json=disableMemoryLimit,proto3" json:"disable_memory_limit,omitempty"`
	DelayStart             bool                   `protobuf:"varint,4,opt,name=delay_start,json=delayStart,proto3" json:"delay_start,omitempty"`
	EnableOldCommandServer bool                   `protobuf:"varint,5,opt,name=enable_old_command_server,json=enableOldCommandServer,proto3" json:"enable_old_command_server,omitempty"`
	EnableRawConfig        bool                   `protobuf:"varint,6,opt,name=enable_raw_config,json=enableRawConfig,proto3" json:"enable_raw_config,omitempty"`
	ConfigName             string                 `protobuf:"bytes,7,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{1}
}

func (x *StartRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *StartRequest) GetConfigContent() string {
	if x != nil {
		return x.ConfigContent
	}
	return ""
}

func (x *StartRequest) GetDisableMemoryLimit() bool {
	if x != nil {
		return x.DisableMemoryLimit
	}
	return false
}

func (x *StartRequest) GetDelayStart() bool {
	if x != nil {
		return x.DelayStart
	}
	return false
}

func (x *StartRequest) GetEnableOldCommandServer() bool {
	if x != nil {
		return x.EnableOldCommandServer
	}
	return false
}

func (x *StartRequest) GetEnableRawConfig() bool {
	if x != nil {
		return x.EnableRawConfig
	}
	return false
}

func (x *StartRequest) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          SetupMode              `protobuf:"varint,1,opt,name=mode,proto3,enum=hcore.SetupMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{2}
}

func (x *CloseRequest) GetMode() SetupMode {
	if x != nil {
		return x.Mode
	}
	return SetupMode_OLD
}

// Define the message equivalent of SetupParameters
type SetupRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BasePath          string                 `protobuf:"bytes,1,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	WorkingDir        string                 `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	TempDir           string                 `protobuf:"bytes,3,opt,name=temp_dir,json=tempDir,proto3" json:"temp_dir,omitempty"`
	FlutterStatusPort int64                  `protobuf:"varint,4,opt,name=flutter_status_port,json=flutterStatusPort,proto3" json:"flutter_status_port,omitempty"`
	Listen            string                 `protobuf:"bytes,5,opt,name=listen,proto3" json:"listen,omitempty"`
	Secret            string                 `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	Debug             bool                   `protobuf:"varint,7,opt,name=debug,proto3" json:"debug,omitempty"`
	Mode              SetupMode              `protobuf:"varint,8,opt,name=mode,proto3,enum=hcore.SetupMode" json:"mode,omitempty"`
	FixAndroidStack   bool                   `protobuf:"varint,9,opt,name=fix_android_stack,json=fixAndroidStack,proto3" json:"fix_android_stack,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetupRequest) Reset() {
	*x = SetupRequest{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRequest) ProtoMessage() {}

func (x *SetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRequest.ProtoReflect.Descriptor instead.
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{3}
}

func (x *SetupRequest) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *SetupRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *SetupRequest) GetTempDir() string {
	if x != nil {
		return x.TempDir
	}
	return ""
}

func (x *SetupRequest) GetFlutterStatusPort() int64 {
	if x != nil {
		return x.FlutterStatusPort
	}
	return 0
}

func (x *SetupRequest) GetListen() string {
	if x != nil {
		return x.Listen
	}
	return ""
}

func (x *SetupRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *SetupRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *SetupRequest) GetMode() SetupMode {
	if x != nil {
		return x.Mode
	}
	return SetupMode_OLD
}

func (x *SetupRequest) GetFixAndroidStack() bool {
	if x != nil {
		return x.FixAndroidStack
	}
	return false
}

type SystemInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Memory           int64                  `protobuf:"varint,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Goroutines       int32                  `protobuf:"varint,2,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	ConnectionsIn    int32                  `protobuf:"varint,3,opt,name=connections_in,json=connectionsIn,proto3" json:"connections_in,omitempty"`
	ConnectionsOut   int32                  `protobuf:"varint,4,opt,name=connections_out,json=connectionsOut,proto3" json:"connections_out,omitempty"`
	TrafficAvailable bool                   `protobuf:"varint,5,opt,name=traffic_available,json=trafficAvailable,proto3" json:"traffic_available,omitempty"`
	Uplink           int64                  `protobuf:"varint,6,opt,name=uplink,proto3" json:"uplink,omitempty"`
	Downlink         int64                  `protobuf:"varint,7,opt,name=downlink,proto3" json:"downlink,omitempty"`
	UplinkTotal      int64                  `protobuf:"varint,8,opt,name=uplink_total,json=uplinkTotal,proto3" json:"uplink_total,omitempty"`
	DownlinkTotal    int64                  `protobuf:"varint,9,opt,name=downlink_total,json=downlinkTotal,proto3" json:"downlink_total,omitempty"`
	CurrentOutbound  string                 `protobuf:"bytes,10,opt,name=current_outbound,json=currentOutbound,proto3" json:"current_outbound,omitempty"`
	CurrentProfile   string                 `protobuf:"bytes,11,opt,name=current_profile,json=currentProfile,proto3" json:"current_profile,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{4}
}

func (x *SystemInfo) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *SystemInfo) GetGoroutines() int32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *SystemInfo) GetConnectionsIn() int32 {
	if x != nil {
		return x.ConnectionsIn
	}
	return 0
}

func (x *SystemInfo) GetConnectionsOut() int32 {
	if x != nil {
		return x.ConnectionsOut
	}
	return 0
}

func (x *SystemInfo) GetTrafficAvailable() bool {
	if x != nil {
		return x.TrafficAvailable
	}
	return false
}

func (x *SystemInfo) GetUplink() int64 {
	if x != nil {
		return x.Uplink
	}
	return 0
}

func (x *SystemInfo) GetDownlink() int64 {
	if x != nil {
		return x.Downlink
	}
	return 0
}

func (x *SystemInfo) GetUplinkTotal() int64 {
	if x != nil {
		return x.UplinkTotal
	}
	return 0
}

func (x *SystemInfo) GetDownlinkTotal() int64 {
	if x != nil {
		return x.DownlinkTotal
	}
	return 0
}

func (x *SystemInfo) GetCurrentOutbound() string {
	if x != nil {
		return x.CurrentOutbound
	}
	return ""
}

func (x *SystemInfo) GetCurrentProfile() string {
	if x != nil {
		return x.CurrentProfile
	}
	return ""
}

type OutboundInfo struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Tag                     string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type                    string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	UrlTestTime             *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=url_test_time,json=urlTestTime,proto3" json:"url_test_time,omitempty"`
	UrlTestDelay            int32                  `protobuf:"varint,4,opt,name=url_test_delay,json=urlTestDelay,proto3" json:"url_test_delay,omitempty"`
	Ipinfo                  *IpInfo                `protobuf:"bytes,5,opt,name=ipinfo,proto3,oneof" json:"ipinfo,omitempty"`
	IsSelected              bool                   `protobuf:"varint,6,opt,name=is_selected,json=isSelected,proto3" json:"is_selected,omitempty"`
	IsGroup                 bool                   `protobuf:"varint,7,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"`
	GroupSelectedTag        *string                `protobuf:"bytes,13,opt,name=group_selected_tag,json=groupSelectedTag,proto3,oneof" json:"group_selected_tag,omitempty"`
	GroupSelectedTagDisplay *string                `protobuf:"bytes,14,opt,name=group_selected_tag_display,json=groupSelectedTagDisplay,proto3,oneof" json:"group_selected_tag_display,omitempty"`
	IsSecure                bool                   `protobuf:"varint,8,opt,name=is_secure,json=isSecure,proto3" json:"is_secure,omitempty"`
	IsVisible               bool                   `protobuf:"varint,9,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	Port                    uint32                 `protobuf:"varint,10,opt,name=port,proto3" json:"port,omitempty"`
	Host                    string                 `protobuf:"bytes,11,opt,name=host,proto3" json:"host,omitempty"`
	TagDisplay              string                 `protobuf:"bytes,12,opt,name=tag_display,json=tagDisplay,proto3" json:"tag_display,omitempty"`
	Upload                  int64                  `protobuf:"varint,15,opt,name=upload,proto3" json:"upload,omitempty"`
	Download                int64                  `protobuf:"varint,16,opt,name=download,proto3" json:"download,omitempty"`
	Detour                  string                 `protobuf:"bytes,17,opt,name=detour,proto3" json:"detour,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OutboundInfo) Reset() {
	*x = OutboundInfo{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundInfo) ProtoMessage() {}

func (x *OutboundInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundInfo.ProtoReflect.Descriptor instead.
func (*OutboundInfo) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{5}
}

func (x *OutboundInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *OutboundInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OutboundInfo) GetUrlTestTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UrlTestTime
	}
	return nil
}

func (x *OutboundInfo) GetUrlTestDelay() int32 {
	if x != nil {
		return x.UrlTestDelay
	}
	return 0
}

func (x *OutboundInfo) GetIpinfo() *IpInfo {
	if x != nil {
		return x.Ipinfo
	}
	return nil
}

func (x *OutboundInfo) GetIsSelected() bool {
	if x != nil {
		return x.IsSelected
	}
	return false
}

func (x *OutboundInfo) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

func (x *OutboundInfo) GetGroupSelectedTag() string {
	if x != nil && x.GroupSelectedTag != nil {
		return *x.GroupSelectedTag
	}
	return ""
}

func (x *OutboundInfo) GetGroupSelectedTagDisplay() string {
	if x != nil && x.GroupSelectedTagDisplay != nil {
		return *x.GroupSelectedTagDisplay
	}
	return ""
}

func (x *OutboundInfo) GetIsSecure() bool {
	if x != nil {
		return x.IsSecure
	}
	return false
}

func (x *OutboundInfo) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *OutboundInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *OutboundInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *OutboundInfo) GetTagDisplay() string {
	if x != nil {
		return x.TagDisplay
	}
	return ""
}

func (x *OutboundInfo) GetUpload() int64 {
	if x != nil {
		return x.Upload
	}
	return 0
}

func (x *OutboundInfo) GetDownload() int64 {
	if x != nil {
		return x.Download
	}
	return 0
}

func (x *OutboundInfo) GetDetour() string {
	if x != nil {
		return x.Detour
	}
	return ""
}

type IpInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`                     // The IP address.
	CountryCode   string                 `protobuf:"bytes,2,opt,name=country_code,proto3" json:"country_code,omitempty"` // The country code.
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`             // The region (optional).
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`                 // The city (optional).
	Asn           int32                  `protobuf:"varint,5,opt,name=asn,proto3" json:"asn,omitempty"`                  // The Autonomous System Number (optional).
	Org           string                 `protobuf:"bytes,6,opt,name=org,proto3" json:"org,omitempty"`                   // The organization (optional).
	Latitude      float64                `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`       // The latitude (optional).
	Longitude     float64                `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`     // The longitude (optional).
	PostalCode    string                 `protobuf:"bytes,9,opt,name=postal_code,proto3" json:"postal_code,omitempty"`   // The postal code (optional).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpInfo) Reset() {
	*x = IpInfo{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpInfo) ProtoMessage() {}

func (x *IpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpInfo.ProtoReflect.Descriptor instead.
func (*IpInfo) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{6}
}

func (x *IpInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IpInfo) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *IpInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *IpInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *IpInfo) GetAsn() int32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *IpInfo) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *IpInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *IpInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *IpInfo) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type OutboundGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Selected      string                 `protobuf:"bytes,3,opt,name=selected,proto3" json:"selected,omitempty"`
	Selectable    bool                   `protobuf:"varint,4,opt,name=selectable,proto3" json:"selectable,omitempty"`
	IsExpand      bool                   `protobuf:"varint,5,opt,name=Is_expand,json=IsExpand,proto3" json:"Is_expand,omitempty"`
	Items         []*OutboundInfo        `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundGroup) Reset() {
	*x = OutboundGroup{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundGroup) ProtoMessage() {}

func (x *OutboundGroup) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundGroup.ProtoReflect.Descriptor instead.
func (*OutboundGroup) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{7}
}

func (x *OutboundGroup) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *OutboundGroup) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OutboundGroup) GetSelected() string {
	if x != nil {
		return x.Selected
	}
	return ""
}

func (x *OutboundGroup) GetSelectable() bool {
	if x != nil {
		return x.Selectable
	}
	return false
}

func (x *OutboundGroup) GetIsExpand() bool {
	if x != nil {
		return x.IsExpand
	}
	return false
}

func (x *OutboundGroup) GetItems() []*OutboundInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type OutboundGroupList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OutboundGroup       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundGroupList) Reset() {
	*x = OutboundGroupList{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundGroupList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundGroupList) ProtoMessage() {}

func (x *OutboundGroupList) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundGroupList.ProtoReflect.Descriptor instead.
func (*OutboundGroupList) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{8}
}

func (x *OutboundGroupList) GetItems() []*OutboundGroup {
	if x != nil {
		return x.Items
	}
	return nil
}

type WarpAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarpAccount) Reset() {
	*x = WarpAccount{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarpAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarpAccount) ProtoMessage() {}

func (x *WarpAccount) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarpAccount.ProtoReflect.Descriptor instead.
func (*WarpAccount) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{9}
}

func (x *WarpAccount) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *WarpAccount) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type WarpWireguardConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey       string                 `protobuf:"bytes,1,opt,name=private_key,json=private-key,proto3" json:"private_key,omitempty"`
	LocalAddressIpv4 string                 `protobuf:"bytes,2,opt,name=local_address_ipv4,json=local-address-ipv4,proto3" json:"local_address_ipv4,omitempty"`
	LocalAddressIpv6 string                 `protobuf:"bytes,3,opt,name=local_address_ipv6,json=local-address-ipv6,proto3" json:"local_address_ipv6,omitempty"`
	PeerPublicKey    string                 `protobuf:"bytes,4,opt,name=peer_public_key,json=peer-public-key,proto3" json:"peer_public_key,omitempty"`
	ClientId         string                 `protobuf:"bytes,5,opt,name=client_id,json=client-id,proto3" json:"client_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WarpWireguardConfig) Reset() {
	*x = WarpWireguardConfig{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarpWireguardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarpWireguardConfig) ProtoMessage() {}

func (x *WarpWireguardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarpWireguardConfig.ProtoReflect.Descriptor instead.
func (*WarpWireguardConfig) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{10}
}

func (x *WarpWireguardConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *WarpWireguardConfig) GetLocalAddressIpv4() string {
	if x != nil {
		return x.LocalAddressIpv4
	}
	return ""
}

func (x *WarpWireguardConfig) GetLocalAddressIpv6() string {
	if x != nil {
		return x.LocalAddressIpv6
	}
	return ""
}

func (x *WarpWireguardConfig) GetPeerPublicKey() string {
	if x != nil {
		return x.PeerPublicKey
	}
	return ""
}

func (x *WarpWireguardConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type WarpGenerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *WarpAccount           `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Log           string                 `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
	Config        *WarpWireguardConfig   `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarpGenerationResponse) Reset() {
	*x = WarpGenerationResponse{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarpGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarpGenerationResponse) ProtoMessage() {}

func (x *WarpGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarpGenerationResponse.ProtoReflect.Descriptor instead.
func (*WarpGenerationResponse) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{11}
}

func (x *WarpGenerationResponse) GetAccount() *WarpAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *WarpGenerationResponse) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *WarpGenerationResponse) GetConfig() *WarpWireguardConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type SystemProxyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemProxyStatus) Reset() {
	*x = SystemProxyStatus{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemProxyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemProxyStatus) ProtoMessage() {}

func (x *SystemProxyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemProxyStatus.ProtoReflect.Descriptor instead.
func (*SystemProxyStatus) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{12}
}

func (x *SystemProxyStatus) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *SystemProxyStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,2,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	TempPath      string                 `protobuf:"bytes,3,opt,name=temp_path,json=tempPath,proto3" json:"temp_path,omitempty"`
	Debug         bool                   `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{13}
}

func (x *ParseRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ParseRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *ParseRequest) GetTempPath() string {
	if x != nil {
		return x.TempPath
	}
	return ""
}

func (x *ParseRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type ParseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseCode  hcommon.ResponseCode   `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3,enum=hcommon.ResponseCode" json:"response_code,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{14}
}

func (x *ParseResponse) GetResponseCode() hcommon.ResponseCode {
	if x != nil {
		return x.ResponseCode
	}
	return hcommon.ResponseCode(0)
}

func (x *ParseResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ParseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Wave 13D — Bootstrap Subscription Fetch.
// Fetches an HTTP resource (subscription URL) through a temporary side-instance
// sing-box configured from `config_json`. The side-instance is brought up with
// TUN/system-proxy/clash disabled and a SOCKS5 inbound on a random localhost port,
// the request is issued through that SOCKS5, then the side-instance is torn down.
// The main VPN (static.StartedService) is not touched.
type BootstrapFetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // sing-box options JSON (e.g. urltest carousel of bootstrap endpoints)
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`                                 // URL to GET
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`   // 0 = default 30000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapFetchRequest) Reset() {
	*x = BootstrapFetchRequest{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapFetchRequest) ProtoMessage() {}

func (x *BootstrapFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapFetchRequest.ProtoReflect.Descriptor instead.
func (*BootstrapFetchRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{15}
}

func (x *BootstrapFetchRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *BootstrapFetchRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BootstrapFetchRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type BootstrapFetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`                                // raw response body
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP status code (0 if request never reached the server)
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                              // error text (empty on success); transport is always OK = soft error
	DurationMs    int32                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // total time spent for UI loading state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapFetchResponse) Reset() {
	*x = BootstrapFetchResponse{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapFetchResponse) ProtoMessage() {}

func (x *BootstrapFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapFetchResponse.ProtoReflect.Descriptor instead.
func (*BootstrapFetchResponse) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{16}
}

func (x *BootstrapFetchResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *BootstrapFetchResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BootstrapFetchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BootstrapFetchResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ChangeInhiveSettingsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InhiveSettingsJson string                 `protobuf:"bytes,1,opt,name=inhive_settings_json,json=inhiveSettingsJson,proto3" json:"inhive_settings_json,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChangeInhiveSettingsRequest) Reset() {
	*x = ChangeInhiveSettingsRequest{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeInhiveSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeInhiveSettingsRequest) ProtoMessage() {}

func (x *ChangeInhiveSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeInhiveSettingsRequest.ProtoReflect.Descriptor instead.
func (*ChangeInhiveSettingsRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{17}
}

func (x *ChangeInhiveSettingsRequest) GetInhiveSettingsJson() string {
	if x != nil {
		return x.InhiveSettingsJson
	}
	return ""
}

type GenerateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TempPath      string                 `protobuf:"bytes,2,opt,name=temp_path,json=tempPath,proto3" json:"temp_path,omitempty"`
	Debug         bool                   `protobuf:"varint,3,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateConfigRequest) Reset() {
	*x = GenerateConfigRequest{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConfigRequest) ProtoMessage() {}

func (x *GenerateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConfigRequest.ProtoReflect.Descriptor instead.
func (*GenerateConfigRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{18}
}

func (x *GenerateConfigRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GenerateConfigRequest) GetTempPath() string {
	if x != nil {
		return x.TempPath
	}
	return ""
}

func (x *GenerateConfigRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type GenerateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigContent string                 `protobuf:"bytes,1,opt,name=config_content,json=configContent,proto3" json:"config_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateConfigResponse) Reset() {
	*x = GenerateConfigResponse{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConfigResponse) ProtoMessage() {}

func (x *GenerateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConfigResponse.ProtoReflect.Descriptor instead.
func (*GenerateConfigResponse) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{19}
}

func (x *GenerateConfigResponse) GetConfigContent() string {
	if x != nil {
		return x.ConfigContent
	}
	return ""
}

type SelectOutboundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupTag      string                 `protobuf:"bytes,1,opt,name=group_tag,json=groupTag,proto3" json:"group_tag,omitempty"`
	OutboundTag   string                 `protobuf:"bytes,2,opt,name=outbound_tag,json=outboundTag,proto3" json:"outbound_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectOutboundRequest) Reset() {
	*x = SelectOutboundRequest{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectOutboundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectOutboundRequest) ProtoMessage() {}

func (x *SelectOutboundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectOutboundRequest.ProtoReflect.Descriptor instead.
func (*SelectOutboundRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{20}
}

func (x *SelectOutboundRequest) GetGroupTag() string {
	if x != nil {
		return x.GroupTag
	}
	return ""
}

func (x *SelectOutboundRequest) GetOutboundTag() string {
	if x != nil {
		return x.OutboundTag
	}
	return ""
}

type UrlTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlTestRequest) Reset() {
	*x = UrlTestRequest{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlTestRequest) ProtoMessage() {}

func (x *UrlTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlTestRequest.ProtoReflect.Descriptor instead.
func (*UrlTestRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{21}
}

func (x *UrlTestRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// SpeedTestRequest — измеряет throughput через конкретный outbound.
// Используется UI для "Тест скорости" по серверам подписки.
type SpeedTestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tag outbound'а через который тестируем (например "p-xxx").
	OutboundTag string `protobuf:"bytes,1,opt,name=outbound_tag,json=outboundTag,proto3" json:"outbound_tag,omitempty"`
	// Сколько байт скачать/залить (default 2_000_000 = 2MB).
	TestBytes int64 `protobuf:"varint,2,opt,name=test_bytes,json=testBytes,proto3" json:"test_bytes,omitempty"`
	// Тестировать download (false) или upload (true). Default download.
	Upload bool `protobuf:"varint,3,opt,name=upload,proto3" json:"upload,omitempty"`
	// Timeout сек (default 20). Long timeout важен на slow connections.
	TimeoutSec    int32 `protobuf:"varint,4,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeedTestRequest) Reset() {
	*x = SpeedTestRequest{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedTestRequest) ProtoMessage() {}

func (x *SpeedTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedTestRequest.ProtoReflect.Descriptor instead.
func (*SpeedTestRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{22}
}

func (x *SpeedTestRequest) GetOutboundTag() string {
	if x != nil {
		return x.OutboundTag
	}
	return ""
}

func (x *SpeedTestRequest) GetTestBytes() int64 {
	if x != nil {
		return x.TestBytes
	}
	return 0
}

func (x *SpeedTestRequest) GetUpload() bool {
	if x != nil {
		return x.Upload
	}
	return false
}

func (x *SpeedTestRequest) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

type SpeedTestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Скорость в килобайтах/сек (KB/s). 0 если test failed.
	SpeedKbps int64 `protobuf:"varint,1,opt,name=speed_kbps,json=speedKbps,proto3" json:"speed_kbps,omitempty"`
	// Время теста в миллисекундах (для diagnostic).
	ElapsedMs int64 `protobuf:"varint,2,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	// Сколько байт реально получено/отправлено.
	BytesTransferred int64 `protobuf:"varint,3,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	// Error message если test failed (empty on success).
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeedTestResponse) Reset() {
	*x = SpeedTestResponse{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedTestResponse) ProtoMessage() {}

func (x *SpeedTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedTestResponse.ProtoReflect.Descriptor instead.
func (*SpeedTestResponse) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{23}
}

func (x *SpeedTestResponse) GetSpeedKbps() int64 {
	if x != nil {
		return x.SpeedKbps
	}
	return 0
}

func (x *SpeedTestResponse) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *SpeedTestResponse) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *SpeedTestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GenerateWarpConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseKey    string                 `protobuf:"bytes,1,opt,name=license_key,json=licenseKey,proto3" json:"license_key,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateWarpConfigRequest) Reset() {
	*x = GenerateWarpConfigRequest{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateWarpConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateWarpConfigRequest) ProtoMessage() {}

func (x *GenerateWarpConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateWarpConfigRequest.ProtoReflect.Descriptor instead.
func (*GenerateWarpConfigRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{24}
}

func (x *GenerateWarpConfigRequest) GetLicenseKey() string {
	if x != nil {
		return x.LicenseKey
	}
	return ""
}

func (x *GenerateWarpConfigRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GenerateWarpConfigRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type SetSystemProxyEnabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnabled     bool                   `protobuf:"varint,1,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSystemProxyEnabledRequest) Reset() {
	*x = SetSystemProxyEnabledRequest{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSystemProxyEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSystemProxyEnabledRequest) ProtoMessage() {}

func (x *SetSystemProxyEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSystemProxyEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetSystemProxyEnabledRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{25}
}

func (x *SetSystemProxyEnabledRequest) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=hcore.LogLevel" json:"level,omitempty"`
	Type          LogType                `protobuf:"varint,2,opt,name=type,proto3,enum=hcore.LogType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{26}
}

func (x *LogMessage) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_TRACE
}

func (x *LogMessage) GetType() LogType {
	if x != nil {
		return x.Type
	}
	return LogType_CORE
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogMessage) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=hcore.LogLevel" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{27}
}

func (x *LogRequest) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_TRACE
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_v2_hcore_hcore_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_hcore_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_hcore_proto_rawDescGZIP(), []int{28}
}

var File_v2_hcore_hcore_proto protoreflect.FileDescriptor

const file_v2_hcore_hcore_proto_rawDesc = "" +
	"\n" +
	"\x14v2/hcore/hcore.proto\x12\x05hcore\x1a\x17v2/hcommon/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x01\n" +
	"\x10CoreInfoResponse\x120\n" +
	"\n" +
	"core_state\x18\x01 \x01(\x0e2\x11.hcore.CoreStatesR\tcoreState\x125\n" +
	"\fmessage_type\x18\x02 \x01(\x0e2\x12.hcore.MessageTypeR\vmessageType\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xb1\x02\n" +
	"\fStartRequest\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\x12%\n" +
	"\x0econfig_content\x18\x02 \x01(\tR\rconfigContent\x120\n" +
	"\x14disable_memory_limit\x18\x03 \x01(\bR\x12disableMemoryLimit\x12\x1f\n" +
	"\vdelay_start\x18\x04 \x01(\bR\n" +
	"delayStart\x129\n" +
	"\x19enable_old_command_server\x18\x05 \x01(\bR\x16enableOldCommandServer\x12*\n" +
	"\x11enable_raw_config\x18\x06 \x01(\bR\x0fenableRawConfig\x12\x1f\n" +
	"\vconfig_name\x18\a \x01(\tR\n" +
	"configName\"4\n" +
	"\fCloseRequest\x12$\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x10.hcore.SetupModeR\x04mode\"\xaf\x02\n" +
	"\fSetupRequest\x12\x1b\n" +
	"\tbase_path\x18\x01 \x01(\tR\bbasePath\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\x12\x19\n" +
	"\btemp_dir\x18\x03 \x01(\tR\atempDir\x12.\n" +
	"\x13flutter_status_port\x18\x04 \x01(\x03R\x11flutterStatusPort\x12\x16\n" +
	"\x06listen\x18\x05 \x01(\tR\x06listen\x12\x16\n" +
	"\x06secret\x18\x06 \x01(\tR\x06secret\x12\x14\n" +
	"\x05debug\x18\a \x01(\bR\x05debug\x12$\n" +
	"\x04mode\x18\b \x01(\x0e2\x10.hcore.SetupModeR\x04mode\x12*\n" +
	"\x11fix_android_stack\x18\t \x01(\bR\x0ffixAndroidStack\"\x93\x03\n" +
	"\n" +
	"SystemInfo\x12\x16\n" +
	"\x06memory\x18\x01 \x01(\x03R\x06memory\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x02 \x01(\x05R\n" +
	"goroutines\x12%\n" +
	"\x0econnections_in\x18\x03 \x01(\x05R\rconnectionsIn\x12'\n" +
	"\x0fconnections_out\x18\x04 \x01(\x05R\x0econnectionsOut\x12+\n" +
	"\x11traffic_available\x18\x05 \x01(\bR\x10trafficAvailable\x12\x16\n" +
	"\x06uplink\x18\x06 \x01(\x03R\x06uplink\x12\x1a\n" +
	"\bdownlink\x18\a \x01(\x03R\bdownlink\x12!\n" +
	"\fuplink_total\x18\b \x01(\x03R\vuplinkTotal\x12%\n" +
	"\x0edownlink_total\x18\t \x01(\x03R\rdownlinkTotal\x12)\n" +
	"\x10current_outbound\x18\n" +
	" \x01(\tR\x0fcurrentOutbound\x12'\n" +
	"\x0fcurrent_profile\x18\v \x01(\tR\x0ecurrentProfile\"\x89\x05\n" +
	"\fOutboundInfo\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12>\n" +
	"\rurl_test_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vurlTestTime\x12$\n" +
	"\x0eurl_test_delay\x18\x04 \x01(\x05R\furlTestDelay\x12*\n" +
	"\x06ipinfo\x18\x05 \x01(\v2\r.hcore.IpInfoH\x00R\x06ipinfo\x88\x01\x01\x12\x1f\n" +
	"\vis_selected\x18\x06 \x01(\bR\n" +
	"isSelected\x12\x19\n" +
	"\bis_group\x18\a \x01(\bR\aisGroup\x121\n" +
	"\x12group_selected_tag\x18\r \x01(\tH\x01R\x10groupSelectedTag\x88\x01\x01\x12@\n" +
	"\x1agroup_selected_tag_display\x18\x0e \x01(\tH\x02R\x17groupSelectedTagDisplay\x88\x01\x01\x12\x1b\n" +
	"\tis_secure\x18\b \x01(\bR\bisSecure\x12\x1d\n" +
	"\n" +
	"is_visible\x18\t \x01(\bR\tisVisible\x12\x12\n" +
	"\x04port\x18\n" +
	" \x01(\rR\x04port\x12\x12\n" +
	"\x04host\x18\v \x01(\tR\x04host\x12\x1f\n" +
	"\vtag_display\x18\f \x01(\tR\n" +
	"tagDisplay\x12\x16\n" +
	"\x06upload\x18\x0f \x01(\x03R\x06upload\x12\x1a\n" +
	"\bdownload\x18\x10 \x01(\x03R\bdownload\x12\x16\n" +
	"\x06detour\x18\x11 \x01(\tR\x06detourB\t\n" +
	"\a_ipinfoB\x15\n" +
	"\x13_group_selected_tagB\x1d\n" +
	"\x1b_group_selected_tag_display\"\xe8\x01\n" +
	"\x06IpInfo\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\"\n" +
	"\fcountry_code\x18\x02 \x01(\tR\fcountry_code\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x10\n" +
	"\x03asn\x18\x05 \x01(\x05R\x03asn\x12\x10\n" +
	"\x03org\x18\x06 \x01(\tR\x03org\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x01R\tlongitude\x12 \n" +
	"\vpostal_code\x18\t \x01(\tR\vpostal_code\"\xb9\x01\n" +
	"\rOutboundGroup\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bselected\x18\x03 \x01(\tR\bselected\x12\x1e\n" +
	"\n" +
	"selectable\x18\x04 \x01(\bR\n" +
	"selectable\x12\x1b\n" +
	"\tIs_expand\x18\x05 \x01(\bR\bIsExpand\x12)\n" +
	"\x05items\x18\x06 \x03(\v2\x13.hcore.OutboundInfoR\x05items\"?\n" +
	"\x11OutboundGroupList\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.hcore.OutboundGroupR\x05items\"O\n" +
	"\vWarpAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"\xdf\x01\n" +
	"\x13WarpWireguardConfig\x12 \n" +
	"\vprivate_key\x18\x01 \x01(\tR\vprivate-key\x12.\n" +
	"\x12local_address_ipv4\x18\x02 \x01(\tR\x12local-address-ipv4\x12.\n" +
	"\x12local_address_ipv6\x18\x03 \x01(\tR\x12local-address-ipv6\x12(\n" +
	"\x0fpeer_public_key\x18\x04 \x01(\tR\x0fpeer-public-key\x12\x1c\n" +
	"\tclient_id\x18\x05 \x01(\tR\tclient-id\"\x8c\x01\n" +
	"\x16WarpGenerationResponse\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.hcore.WarpAccountR\aaccount\x12\x10\n" +
	"\x03log\x18\x02 \x01(\tR\x03log\x122\n" +
	"\x06config\x18\x03 \x01(\v2\x1a.hcore.WarpWireguardConfigR\x06config\"K\n" +
	"\x11SystemProxyStatus\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"|\n" +
	"\fParseRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1f\n" +
	"\vconfig_path\x18\x02 \x01(\tR\n" +
	"configPath\x12\x1b\n" +
	"\ttemp_path\x18\x03 \x01(\tR\btempPath\x12\x14\n" +
	"\x05debug\x18\x04 \x01(\bR\x05debug\"\x7f\n" +
	"\rParseResponse\x12:\n" +
	"\rresponse_code\x18\x01 \x01(\x0e2\x15.hcommon.ResponseCodeR\fresponseCode\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"i\n" +
	"\x15BootstrapFetchRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\"\x84\x01\n" +
	"\x16BootstrapFetchResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x05R\n" +
	"durationMs\"O\n" +
	"\x1bChangeInhiveSettingsRequest\x120\n" +
	"\x14inhive_settings_json\x18\x01 \x01(\tR\x12inhiveSettingsJson\"^\n" +
	"\x15GenerateConfigRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\ttemp_path\x18\x02 \x01(\tR\btempPath\x12\x14\n" +
	"\x05debug\x18\x03 \x01(\bR\x05debug\"?\n" +
	"\x16GenerateConfigResponse\x12%\n" +
	"\x0econfig_content\x18\x01 \x01(\tR\rconfigContent\"W\n" +
	"\x15SelectOutboundRequest\x12\x1b\n" +
	"\tgroup_tag\x18\x01 \x01(\tR\bgroupTag\x12!\n" +
	"\foutbound_tag\x18\x02 \x01(\tR\voutboundTag\"\"\n" +
	"\x0eUrlTestRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\"\x8d\x01\n" +
	"\x10SpeedTestRequest\x12!\n" +
	"\foutbound_tag\x18\x01 \x01(\tR\voutboundTag\x12\x1d\n" +
	"\n" +
	"test_bytes\x18\x02 \x01(\x03R\ttestBytes\x12\x16\n" +
	"\x06upload\x18\x03 \x01(\bR\x06upload\x12\x1f\n" +
	"\vtimeout_sec\x18\x04 \x01(\x05R\n" +
	"timeoutSec\"\x94\x01\n" +
	"\x11SpeedTestResponse\x12\x1d\n" +
	"\n" +
	"speed_kbps\x18\x01 \x01(\x03R\tspeedKbps\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x02 \x01(\x03R\telapsedMs\x12+\n" +
	"\x11bytes_transferred\x18\x03 \x01(\x03R\x10bytesTransferred\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"~\n" +
	"\x19GenerateWarpConfigRequest\x12\x1f\n" +
	"\vlicense_key\x18\x01 \x01(\tR\n" +
	"licenseKey\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\"=\n" +
	"\x1cSetSystemProxyEnabledRequest\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\x01 \x01(\bR\tisEnabled\"\xa1\x01\n" +
	"\n" +
	"LogMessage\x12%\n" +
	"\x05level\x18\x01 \x01(\x0e2\x0f.hcore.LogLevelR\x05level\x12\"\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0e.hcore.LogTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"3\n" +
	"\n" +
	"LogRequest\x12%\n" +
	"\x05level\x18\x01 \x01(\x0e2\x0f.hcore.LogLevelR\x05level\"\r\n" +
	"\vStopRequest*B\n" +
	"\n" +
	"CoreStates\x12\v\n" +
	"\aSTOPPED\x10\x00\x12\f\n" +
	"\bSTARTING\x10\x01\x12\v\n" +
	"\aSTARTED\x10\x02\x12\f\n" +
	"\bSTOPPING\x10\x03*\xe2\x02\n" +
	"\vMessageType\x12\t\n" +
	"\x05EMPTY\x10\x00\x12\x17\n" +
	"\x13EMPTY_CONFIGURATION\x10\x01\x12\x18\n" +
	"\x14START_COMMAND_SERVER\x10\x02\x12\x12\n" +
	"\x0eCREATE_SERVICE\x10\x03\x12\x11\n" +
	"\rSTART_SERVICE\x10\x04\x12\x14\n" +
	"\x10UNEXPECTED_ERROR\x10\x05\x12\x13\n" +
	"\x0fALREADY_STARTED\x10\x06\x12\x13\n" +
	"\x0fALREADY_STOPPED\x10\a\x12\x16\n" +
	"\x12INSTANCE_NOT_FOUND\x10\b\x12\x18\n" +
	"\x14INSTANCE_NOT_STOPPED\x10\t\x12\x18\n" +
	"\x14INSTANCE_NOT_STARTED\x10\n" +
	"\x12\x19\n" +
	"\x15ERROR_BUILDING_CONFIG\x10\v\x12\x18\n" +
	"\x14ERROR_PARSING_CONFIG\x10\f\x12\x18\n" +
	"\x14ERROR_READING_CONFIG\x10\r\x12\x13\n" +
	"\x0fERROR_EXTENSION\x10\x0e*r\n" +
	"\tSetupMode\x12\a\n" +
	"\x03OLD\x10\x00\x12\x0f\n" +
	"\vGRPC_NORMAL\x10\x01\x12\x13\n" +
	"\x0fGRPC_BACKGROUND\x10\x02\x12\x18\n" +
	"\x14GRPC_NORMAL_INSECURE\x10\x03\x12\x1c\n" +
	"\x18GRPC_BACKGROUND_INSECURE\x10\x04*M\n" +
	"\bLogLevel\x12\t\n" +
	"\x05TRACE\x10\x00\x12\t\n" +
	"\x05DEBUG\x10\x01\x12\b\n" +
	"\x04INFO\x10\x02\x12\v\n" +
	"\aWARNING\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\t\n" +
	"\x05FATAL\x10\x05*,\n" +
	"\aLogType\x12\b\n" +
	"\x04CORE\x10\x00\x12\v\n" +
	"\aSERVICE\x10\x01\x12\n" +
	"\n" +
	"\x06CONFIG\x10\x02BH\n" +
	"\x1ccom.inhive.core.api.v2.hcoreZ(github.com/TwilgateLabs/inhive-core/v2/hcoreb\x06proto3"

var (
	file_v2_hcore_hcore_proto_rawDescOnce sync.Once
	file_v2_hcore_hcore_proto_rawDescData []byte
)

func file_v2_hcore_hcore_proto_rawDescGZIP() []byte {
	file_v2_hcore_hcore_proto_rawDescOnce.Do(func() {
		file_v2_hcore_hcore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_hcore_hcore_proto_rawDesc), len(file_v2_hcore_hcore_proto_rawDesc)))
	})
	return file_v2_hcore_hcore_proto_rawDescData
}

var file_v2_hcore_hcore_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_v2_hcore_hcore_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_v2_hcore_hcore_proto_goTypes = []any{
	(CoreStates)(0),                      // 0: hcore.CoreStates
	(MessageType)(0),                     // 1: hcore.MessageType
	(SetupMode)(0),                       // 2: hcore.SetupMode
	(LogLevel)(0),                        // 3: hcore.LogLevel
	(LogType)(0),                         // 4: hcore.LogType
	(*CoreInfoResponse)(nil),             // 5: hcore.CoreInfoResponse
	(*StartRequest)(nil),                 // 6: hcore.StartRequest
	(*CloseRequest)(nil),                 // 7: hcore.CloseRequest
	(*SetupRequest)(nil),                 // 8: hcore.SetupRequest
	(*SystemInfo)(nil),                   // 9: hcore.SystemInfo
	(*OutboundInfo)(nil),                 // 10: hcore.OutboundInfo
	(*IpInfo)(nil),                       // 11: hcore.IpInfo
	(*OutboundGroup)(nil),                // 12: hcore.OutboundGroup
	(*OutboundGroupList)(nil),            // 13: hcore.OutboundGroupList
	(*WarpAccount)(nil),                  // 14: hcore.WarpAccount
	(*WarpWireguardConfig)(nil),          // 15: hcore.WarpWireguardConfig
	(*WarpGenerationResponse)(nil),       // 16: hcore.WarpGenerationResponse
	(*SystemProxyStatus)(nil),            // 17: hcore.SystemProxyStatus
	(*ParseRequest)(nil),                 // 18: hcore.ParseRequest
	(*ParseResponse)(nil),                // 19: hcore.ParseResponse
	(*BootstrapFetchRequest)(nil),        // 20: hcore.BootstrapFetchRequest
	(*BootstrapFetchResponse)(nil),       // 21: hcore.BootstrapFetchResponse
	(*ChangeInhiveSettingsRequest)(nil),  // 22: hcore.ChangeInhiveSettingsRequest
	(*GenerateConfigRequest)(nil),        // 23: hcore.GenerateConfigRequest
	(*GenerateConfigResponse)(nil),       // 24: hcore.GenerateConfigResponse
	(*SelectOutboundRequest)(nil),        // 25: hcore.SelectOutboundRequest
	(*UrlTestRequest)(nil),               // 26: hcore.UrlTestRequest
	(*SpeedTestRequest)(nil),             // 27: hcore.SpeedTestRequest
	(*SpeedTestResponse)(nil),            // 28: hcore.SpeedTestResponse
	(*GenerateWarpConfigRequest)(nil),    // 29: hcore.GenerateWarpConfigRequest
	(*SetSystemProxyEnabledRequest)(nil), // 30: hcore.SetSystemProxyEnabledRequest
	(*LogMessage)(nil),                   // 31: hcore.LogMessage
	(*LogRequest)(nil),                   // 32: hcore.LogRequest
	(*StopRequest)(nil),                  // 33: hcore.StopRequest
	(*timestamppb.Timestamp)(nil),        // 34: google.protobuf.Timestamp
	(hcommon.ResponseCode)(0),            // 35: hcommon.ResponseCode
}
var file_v2_hcore_hcore_proto_depIdxs = []int32{
	0,  // 0: hcore.CoreInfoResponse.core_state:type_name -> hcore.CoreStates
	1,  // 1: hcore.CoreInfoResponse.message_type:type_name -> hcore.MessageType
	2,  // 2: hcore.CloseRequest.mode:type_name -> hcore.SetupMode
	2,  // 3: hcore.SetupRequest.mode:type_name -> hcore.SetupMode
	34, // 4: hcore.OutboundInfo.url_test_time:type_name -> google.protobuf.Timestamp
	11, // 5: hcore.OutboundInfo.ipinfo:type_name -> hcore.IpInfo
	10, // 6: hcore.OutboundGroup.items:type_name -> hcore.OutboundInfo
	12, // 7: hcore.OutboundGroupList.items:type_name -> hcore.OutboundGroup
	14, // 8: hcore.WarpGenerationResponse.account:type_name -> hcore.WarpAccount
	15, // 9: hcore.WarpGenerationResponse.config:type_name -> hcore.WarpWireguardConfig
	35, // 10: hcore.ParseResponse.response_code:type_name -> hcommon.ResponseCode
	3,  // 11: hcore.LogMessage.level:type_name -> hcore.LogLevel
	4,  // 12: hcore.LogMessage.type:type_name -> hcore.LogType
	34, // 13: hcore.LogMessage.time:type_name -> google.protobuf.Timestamp
	3,  // 14: hcore.LogRequest.level:type_name -> hcore.LogLevel
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_v2_hcore_hcore_proto_init() }
func file_v2_hcore_hcore_proto_init() {
	if File_v2_hcore_hcore_proto != nil {
		return
	}
	file_v2_hcore_hcore_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_hcore_hcore_proto_rawDesc), len(file_v2_hcore_hcore_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_hcore_hcore_proto_goTypes,
		DependencyIndexes: file_v2_hcore_hcore_proto_depIdxs,
		EnumInfos:         file_v2_hcore_hcore_proto_enumTypes,
		MessageInfos:      file_v2_hcore_hcore_proto_msgTypes,
	}.Build()
	File_v2_hcore_hcore_proto = out.File
	file_v2_hcore_hcore_proto_goTypes = nil
	file_v2_hcore_hcore_proto_depIdxs = nil
}
